name: Build Check for Linux/Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            label: Windows
            target: x86_64-pc-windows-msvc
            suffix: .exe

    runs-on: ${{ matrix.os }}
    
    env:
      CARGO_TERM_COLOR: always
      BINARY_NAME: 'manget${{ matrix.suffix }}'

    steps:
    - uses: actions/checkout@v2
    - name: 'Build ${{ matrix.label }} Release'
      run: cargo build --release --target ${{ matrix.target }}
