name: Build Linux/Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      BINARY_NAME: manget

    steps:
    - uses: actions/checkout@v2
    - name: Build Linux Release
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Build Windows Release
      run: cargo build --release --target x86_64-pc-windows-msvc
